"use client";

import React, { useState, useEffect } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";
import { api } from "@/app/lib/api";
import {
  ArrowLeft,
  Calendar,
  Phone,
  Mail,
  Clock,
  Sparkles,
  MapPin,
  CircleDollarSign,
  Briefcase,
  Flame,
  CheckCircle,
  MessageSquare,
  Play,
  Pause,
  AlertCircle,
  Share2,
  Trash2,
  UserCheck,
  Send,
  ChevronDown,
  Plus,
  Loader2,
  Edit3,
} from "lucide-react";

export default function LeadDetailPage() {
  const params = useParams();
  const router = useRouter();
  const [lead, setLead] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState<string>("transcript");
  const [isPlaying, setIsPlaying] = useState(false);
  const [noteText, setNoteText] = useState("");
  const [notes, setNotes] = useState<any[]>([]);
  const [role, setRole] = useState("Admin");
  const [statusUpdating, setStatusUpdating] = useState(false);
  const [showBookModal, setShowBookModal] = useState(false);
  const [bookingForm, setBookingForm] = useState({ type: "Site Visit", slot_datetime: "", notes: "" });
  const [booking, setBooking] = useState(false);
  const [bookSuccess, setBookSuccess] = useState(false);

  useEffect(() => {
    setRole(localStorage.getItem("userRole") || "Admin");
    const id = params.id as string;
    
    async function loadLead() {
      try {
        const foundLead = await api.getLead(id);
        
        // Map database lead object to what the page UI expects
        const mappedLead = {
          id: foundLead.id,
          name: foundLead.name,
          phone: foundLead.phone,
          email: foundLead.email || "No email provided",
          propertyType: foundLead.property_type || "Any Property",
          location: foundLead.location || "Not specified",
          budget: foundLead.budget || "No budget set",
          timeline: foundLead.timeline || "Browsing",
          score: foundLead.score || 0,
          scoreCategory: foundLead.score_category || "Cold",
          status: foundLead.status,
          created: new Date(foundLead.created_at).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }),
          
          // Map calls and transcriptions
          intent: foundLead.calls?.[0]?.ai_intent || "Buying intent analysis pending first customer call.",
          aiSummary: foundLead.calls?.[0]?.ai_summary || "Call summary will be auto-generated by the AI virtual receptionist once the first inbound/outbound call connects.",
          actionItem: foundLead.status === "Site Visit Scheduled" 
            ? "Escort client on scheduled site visit. Prepare brochures and contact information for the meeting."
            : foundLead.status === "Callback Requested"
            ? "Follow up via telephone within 24 hours to clarify requirements and pitch model units."
            : "Monitor new lead status. System prompt set to automatically suggest Sunday site visits.",
          
          transcript: foundLead.calls?.[0]?.transcript 
            ? parseTranscript(foundLead.calls[0].transcript)
            : [
                { speaker: "System", text: "No call records exist for this lead yet. Inbound Twilio voice lines will auto-record conversation turns here." }
              ],
              
          appointment: foundLead.appointments?.[0] ? {
            project: foundLead.appointments[0].property_name || "General Project Inquiry",
            date: new Date(foundLead.appointments[0].slot_datetime).toLocaleDateString([], { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }),
            time: new Date(foundLead.appointments[0].slot_datetime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
            status: foundLead.appointments[0].status
          } : null
        };
        
        setLead(mappedLead);
        // Default notes list
        setNotes([
          { author: "AI Receptionist", text: `Lead qualified as ${mappedLead.scoreCategory.toUpperCase()}. Status set to ${mappedLead.status}.`, date: mappedLead.created }
        ]);
      } catch (err) {
        console.error("Failed to load lead details:", err);
      } finally {
        setLoading(false);
      }
    }
    
    if (id) {
      loadLead();
    }
  }, [params]);

  const parseTranscript = (rawTranscript: string) => {
    if (!rawTranscript) return [];
    try {
      return JSON.parse(rawTranscript);
    } catch {
      return rawTranscript.split("\n").map(line => {
        const parts = line.split(":");
        if (parts.length >= 2) {
          return { speaker: parts[0].trim(), text: parts.slice(1).join(":").trim() };
        }
        return { speaker: "System", text: line };
      });
    }
  };

  const handleAddNote = (e: React.FormEvent) => {
    e.preventDefault();
    if (!noteText.trim()) return;

    const newNote = {
      author: localStorage.getItem("userName") || "Sales Executive",
      text: noteText,
      date: new Date().toLocaleString("en-IN", { hour: "numeric", minute: "2-digit", hour12: true, month: "short", day: "numeric", year: "numeric" })
    };

    setNotes([newNote, ...notes]);
    setNoteText("");
  };

  const handleStatusChange = async (newStatus: string) => {
    if (!lead) return;
    setStatusUpdating(true);
    try {
      await api.updateLead(params.id as string, { status: newStatus });
      setLead({ ...lead, status: newStatus });
    } catch (err) {
      alert("Failed to update status.");
    } finally {
      setStatusUpdating(false);
    }
  };

  const handleBookAppointment = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!bookingForm.slot_datetime) return;
    setBooking(true);
    try {
      await api.createAppointment({
        lead_id: params.id as string,
        type: bookingForm.type,
        slot_datetime: new Date(bookingForm.slot_datetime).toISOString(),
        notes: bookingForm.notes || null,
        status: "Pending",
      });
      setBookSuccess(true);
      setShowBookModal(false);
      setBookingForm({ type: "Site Visit", slot_datetime: "", notes: "" });
      // Refresh lead data
      const updated = await api.getLead(params.id as string);
      setLead((prev: any) => ({ ...prev, appointment: updated.appointments?.[0] ? {
        project: updated.appointments[0].property_name || "General Project Inquiry",
        date: new Date(updated.appointments[0].slot_datetime).toLocaleDateString([], { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }),
        time: new Date(updated.appointments[0].slot_datetime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        status: updated.appointments[0].status
      } : prev.appointment }));
      setTimeout(() => setBookSuccess(false), 4000);
    } catch (err: any) {
      alert("Failed to book appointment: " + err.message);
    } finally {
      setBooking(false);
    }
  };

  const handleDelete = async () => {
    if (!lead) return;
    if (confirm(`Are you sure you want to delete lead ${lead.name}?`)) {
      try {
        await api.deleteLead(params.id as string);
        router.push("/dashboard/leads");
      } catch (err) {
        alert("Failed to delete lead: " + err);
      }
    }
  };

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[400px] text-center">
        <span className="w-10 h-10 border-4 border-t-transparent border-electric-500 rounded-full animate-spin" />
        <p className="text-sm text-slate-400 mt-4 font-bold">Loading lead details from database...</p>
      </div>
    );
  }

  if (!lead) {
    return (
      <div className="text-center py-12">
        <p className="text-slate-400 font-bold">Lead profile not found in your database.</p>
        <Link href="/dashboard/leads" className="text-electric-500 hover:underline mt-2 inline-block">
          Return to Leads list
        </Link>
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-in fade-in duration-300">

      {/* Book Appointment Modal */}
      {showBookModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-navy-950/80 backdrop-blur-sm" onClick={() => setShowBookModal(false)} />
          <div className="relative z-10 w-full max-w-md bg-navy-900 border border-navy-800 rounded-2xl shadow-2xl shadow-black/40 animate-in zoom-in-95 duration-200">
            <div className="flex items-center justify-between p-5 border-b border-navy-800">
              <div className="flex items-center gap-2">
                <Calendar className="w-5 h-5 text-electric-500" />
                <h3 className="font-bold text-base">Book Appointment for {lead.name}</h3>
              </div>
              <button onClick={() => setShowBookModal(false)} className="text-slate-400 hover:text-white"><Plus className="w-5 h-5 rotate-45" /></button>
            </div>
            <form onSubmit={handleBookAppointment} className="p-5 space-y-4">
              <div>
                <label className="text-[10px] text-slate-400 uppercase font-bold block mb-1">Appointment Type</label>
                <select
                  value={bookingForm.type}
                  onChange={e => setBookingForm({...bookingForm, type: e.target.value})}
                  className="w-full bg-navy-950 border border-navy-800 rounded-lg p-2.5 text-slate-100 text-xs focus:outline-none focus:border-electric-500"
                >
                  <option>Site Visit</option>
                  <option>Callback</option>
                  <option>Video Call</option>
                </select>
              </div>
              <div>
                <label className="text-[10px] text-slate-400 uppercase font-bold block mb-1">Date & Time</label>
                <input
                  type="datetime-local"
                  required
                  value={bookingForm.slot_datetime}
                  onChange={e => setBookingForm({...bookingForm, slot_datetime: e.target.value})}
                  className="w-full bg-navy-950 border border-navy-800 rounded-lg p-2.5 text-slate-100 text-xs focus:outline-none focus:border-electric-500"
                />
              </div>
              <div>
                <label className="text-[10px] text-slate-400 uppercase font-bold block mb-1">Notes (Optional)</label>
                <input
                  type="text"
                  placeholder="e.g. Client prefers morning slot"
                  value={bookingForm.notes}
                  onChange={e => setBookingForm({...bookingForm, notes: e.target.value})}
                  className="w-full bg-navy-950 border border-navy-800 rounded-lg p-2.5 text-slate-100 placeholder-slate-500 text-xs focus:outline-none focus:border-electric-500"
                />
              </div>
              <div className="flex gap-3 pt-1">
                <button type="button" onClick={() => setShowBookModal(false)} className="flex-1 py-2.5 border border-navy-700 rounded-xl text-xs font-bold text-slate-400 hover:bg-navy-800">Cancel</button>
                <button type="submit" disabled={booking} className="flex-1 py-2.5 bg-electric-500 hover:bg-electric-600 text-white rounded-xl text-xs font-bold flex items-center justify-center gap-2">
                  {booking ? <Loader2 className="w-4 h-4 animate-spin" /> : <Calendar className="w-4 h-4" />}
                  {booking ? "Booking..." : "Confirm Booking"}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Success Banner */}
      {bookSuccess && (
        <div className="p-3 rounded-xl bg-emerald-500/10 border border-emerald-500/25 text-emerald-400 text-xs font-semibold flex items-center gap-2 animate-in fade-in">
          <CheckCircle className="w-4 h-4" />
          Appointment booked successfully! Check the Appointments page to approve it.
        </div>
      )}

      {/* Top Breadcrumb and Actions */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <Link href="/dashboard/leads" className="flex items-center gap-2 text-slate-400 hover:text-white transition-colors text-sm font-semibold">
          <ArrowLeft className="w-4 h-4" />
          <span>Back to Leads</span>
        </Link>

        <div className="flex items-center gap-3">
          {/* Status Change */}
          {(role === "Admin" || role === "Manager") && (
            <div className="relative flex items-center gap-2">
              {statusUpdating && <Loader2 className="w-3.5 h-3.5 text-slate-400 animate-spin" />}
              <select
                value={lead.status}
                onChange={e => handleStatusChange(e.target.value)}
                disabled={statusUpdating}
                className="pl-3 pr-8 py-2 bg-navy-900 border border-navy-800 hover:border-electric-500/50 rounded-xl text-xs font-semibold text-slate-300 focus:outline-none focus:border-electric-500 cursor-pointer appearance-none transition-all"
              >
                <option value="New">New</option>
                <option value="Call Completed">Call Completed</option>
                <option value="Callback Requested">Callback Requested</option>
                <option value="Site Visit Scheduled">Site Visit Scheduled</option>
                <option value="Converted">Converted</option>
                <option value="Lost">Lost</option>
              </select>
              <ChevronDown className="absolute right-2.5 w-3.5 h-3.5 text-slate-400 pointer-events-none" />
            </div>
          )}

          {/* Book Appointment */}
          {(role === "Admin" || role === "Manager") && (
            <button
              onClick={() => setShowBookModal(true)}
              className="flex items-center gap-2 px-4 py-2 bg-electric-600 hover:bg-electric-700 rounded-xl text-xs font-semibold text-white transition-all"
            >
              <Plus className="w-4 h-4" />
              <span>Book Appointment</span>
            </button>
          )}


          <button 
            onClick={handleDelete}
            className="flex items-center gap-2 px-4 py-2 bg-red-500/10 border border-red-500/25 hover:bg-red-500/20 rounded-xl text-xs font-semibold text-red-400 transition-all"
          >
            <Trash2 className="w-4 h-4" />
            <span>Delete</span>
          </button>
        </div>
      </div>

      {/* Main Grid: Info Cards on Left, AI Analysis on Right */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Profile Card & Info */}
        <div className="space-y-6">
          {/* Profile Card */}
          <div className="p-6 rounded-2xl bg-navy-900 border border-navy-800 space-y-6 relative overflow-hidden">
            <div className="absolute right-0 top-0 w-24 h-24 bg-gold-500/5 rounded-full blur-2xl pointer-events-none" />
            
            <div className="flex items-center gap-4">
              <div className="flex items-center justify-center w-14 h-14 rounded-2xl bg-gradient-to-tr from-gold-500 to-electric-500 text-navy-950 font-black text-2xl shadow-lg shadow-gold-500/10">
                {lead.name[0]}
              </div>
              <div>
                <h3 className="text-xl font-bold text-white">{lead.name}</h3>
                <span className="text-xs text-slate-400">ID: {lead.id}</span>
              </div>
            </div>

            <div className="space-y-3 pt-4 border-t border-navy-800 text-sm">
              <div className="flex items-center gap-3 text-slate-300">
                <Phone className="w-4 h-4 text-electric-500" />
                <span>{lead.phone}</span>
              </div>
              <div className="flex items-center gap-3 text-slate-300">
                <Mail className="w-4 h-4 text-electric-500" />
                <span className="truncate">{lead.email}</span>
              </div>
              <div className="flex items-center gap-3 text-slate-300">
                <Clock className="w-4 h-4 text-electric-500" />
                <span>Registered: {lead.created}</span>
              </div>
            </div>

            <div className="flex items-center justify-between p-3.5 bg-navy-950/60 rounded-xl border border-navy-800/80">
              <span className="text-xs font-bold text-slate-400">Lead Score</span>
              <div className="flex items-center gap-1.5 px-3 py-1 rounded-lg bg-navy-900 border border-navy-700 font-extrabold text-amber-500">
                <Flame className="w-4 h-4" />
                <span>{lead.score} / 100</span>
              </div>
            </div>
          </div>

          {/* Requirements Card */}
          <div className="p-6 rounded-2xl bg-navy-900 border border-navy-800 space-y-4">
            <h4 className="font-bold text-base">Requirement Profile</h4>
            
            <div className="space-y-3.5 text-sm">
              <div className="flex items-center justify-between py-2 border-b border-navy-850">
                <span className="text-slate-400 flex items-center gap-2"><Briefcase className="w-4 h-4" /> Property Type</span>
                <span className="font-semibold text-slate-200">{lead.propertyType}</span>
              </div>
              <div className="flex items-center justify-between py-2 border-b border-navy-850">
                <span className="text-slate-400 flex items-center gap-2"><MapPin className="w-4 h-4" /> Preferred Area</span>
                <span className="font-semibold text-slate-200">{lead.location}</span>
              </div>
              <div className="flex items-center justify-between py-2 border-b border-navy-850">
                <span className="text-slate-400 flex items-center gap-2"><CircleDollarSign className="w-4 h-4" /> Budget Limit</span>
                <span className="font-semibold text-slate-200">{lead.budget}</span>
              </div>
              <div className="flex items-center justify-between py-2 border-b border-navy-850">
                <span className="text-slate-400 flex items-center gap-2"><Calendar className="w-4 h-4" /> Purchase Timeline</span>
                <span className="font-semibold text-slate-200">{lead.timeline}</span>
              </div>
            </div>
          </div>

          {/* Appointment/Booking Details */}
          {lead.appointment && (
            <div className="p-6 rounded-2xl bg-emerald-950/20 border border-emerald-500/25 space-y-4">
              <h4 className="font-bold text-base text-emerald-400 flex items-center gap-2">
                <CheckCircle className="w-5 h-5 text-emerald-400" />
                <span>Site Visit Booked</span>
              </h4>
              <div className="space-y-2.5 text-xs leading-relaxed text-slate-300">
                <p><strong>Project:</strong> {lead.appointment.project}</p>
                <p><strong>Scheduled:</strong> {lead.appointment.date} at {lead.appointment.time}</p>
                <p><strong>Status:</strong> <span className="text-emerald-400 font-bold px-1.5 py-0.5 rounded bg-emerald-500/10 border border-emerald-500/20">{lead.appointment.status}</span></p>
              </div>
            </div>
          )}
        </div>

        {/* AI Analytics & Transcripts */}
        <div className="lg:col-span-2 space-y-6">
          {/* AI Analysis Summary */}
          <div className="p-6 rounded-2xl bg-navy-900 border border-navy-800 space-y-6">
            <div className="flex items-center gap-2 pb-2 border-b border-navy-800">
              <Sparkles className="w-5 h-5 text-gold-500 animate-pulse" />
              <h4 className="font-bold text-base bg-gradient-to-r from-gold-400 to-white bg-clip-text text-transparent">AI Receptionist Conversation Analysis</h4>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-sm">
              <div className="space-y-2">
                <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">Customer Buying Intent</span>
                <p className="text-slate-300 leading-relaxed">{lead.intent}</p>
              </div>

              <div className="space-y-2">
                <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">AI Generated Summary</span>
                <p className="text-slate-300 leading-relaxed">{lead.aiSummary}</p>
              </div>
            </div>

            <div className="p-4 rounded-xl bg-gold-500/5 border border-gold-500/15 space-y-2">
              <span className="text-xs font-bold text-gold-500 uppercase tracking-wider flex items-center gap-1.5">
                <AlertCircle className="w-4 h-4" />
                <span>AI Recommended Next Step</span>
              </span>
              <p className="text-sm text-slate-300 leading-relaxed">
                {lead.actionItem}
              </p>
            </div>
          </div>

          {/* Interactive tabs: Transcript vs Custom Notes */}
          <div className="rounded-2xl bg-navy-900 border border-navy-800 overflow-hidden">
            {/* Tab header */}
            <div className="flex border-b border-navy-800 bg-navy-950/40">
              <button
                onClick={() => setActiveTab("transcript")}
                className={`flex-1 py-4 px-6 font-bold text-sm border-b-2 transition-all ${
                  activeTab === "transcript"
                    ? "border-electric-500 text-white bg-navy-900"
                    : "border-transparent text-slate-400 hover:text-slate-200"
                }`}
              >
                Call Recording & Transcript
              </button>
              <button
                onClick={() => setActiveTab("notes")}
                className={`flex-1 py-4 px-6 font-bold text-sm border-b-2 transition-all ${
                  activeTab === "notes"
                    ? "border-electric-500 text-white bg-navy-900"
                    : "border-transparent text-slate-400 hover:text-slate-200"
                }`}
              >
                Executive Action Notes ({notes.length})
              </button>
            </div>

            {/* Tab contents */}
            <div className="p-6">
              {activeTab === "transcript" ? (
                <div className="space-y-6">
                  {/* Mock Audio Player */}
                  <div className="p-4 rounded-xl bg-navy-950/50 border border-navy-850 flex items-center gap-4">
                    <button
                      onClick={() => setIsPlaying(!isPlaying)}
                      className="w-12 h-12 flex-shrink-0 flex items-center justify-center rounded-full bg-electric-500 hover:bg-electric-600 text-white transition-all transform hover:scale-105 active:scale-95 shadow-lg shadow-electric-600/20"
                    >
                      {isPlaying ? <Pause className="w-5 h-5 fill-current" /> : <Play className="w-5 h-5 fill-current pl-0.5" />}
                    </button>
                    <div className="flex-1 space-y-2">
                      <div className="flex justify-between text-xs text-slate-400">
                        <span className="font-semibold text-slate-300">Call Recording Audio</span>
                        <span>0:45 / 2:10</span>
                      </div>
                      
                      {/* Audio waveform mockup in SVG */}
                      <div className="h-6 w-full flex items-center gap-[2px]">
                        {[20, 40, 15, 60, 80, 45, 30, 70, 95, 40, 20, 60, 50, 30, 80, 65, 40, 20, 60, 85, 30, 50, 40, 20, 60, 80, 95, 40, 20, 60, 40, 25, 75, 90, 50, 35, 70, 85, 40, 20, 60, 80, 40, 20, 60, 50].map((h, i) => (
                          <div
                            key={i}
                            className={`w-1 rounded-full transition-all ${
                              i < 15
                                ? "bg-electric-500"
                                : isPlaying && i < 24
                                ? "bg-electric-400/80 animate-pulse"
                                : "bg-navy-800"
                            }`}
                            style={{ height: `${h}%` }}
                          />
                        ))}
                      </div>
                    </div>
                  </div>

                  {/* Transcript dialog list */}
                  <div className="space-y-4 max-h-96 overflow-y-auto pr-2">
                    {lead.transcript.map((line: any, idx: number) => {
                      const isAI = line.speaker === "AI Receptionist";

                      return (
                        <div
                          key={idx}
                          className={`flex gap-3 max-w-[85%] ${isAI ? "mr-auto" : "ml-auto flex-row-reverse"}`}
                        >
                          <div
                            className={`w-7 h-7 rounded-full flex-shrink-0 flex items-center justify-center text-[10px] font-bold ${
                              isAI ? "bg-electric-600 text-white" : "bg-gold-500 text-navy-950"
                            }`}
                          >
                            {isAI ? "AI" : "CU"}
                          </div>
                          <div
                            className={`p-3.5 rounded-2xl text-xs leading-relaxed ${
                              isAI
                                ? "bg-navy-950/60 text-slate-200 rounded-tl-none border border-navy-850"
                                : "bg-electric-600 text-white rounded-tr-none shadow shadow-electric-600/10"
                            }`}
                          >
                            <span className="block text-[10px] font-bold opacity-75 mb-1">{line.speaker}</span>
                            <span>{line.text}</span>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              ) : (
                <div className="space-y-6">
                  {/* Note taking form */}
                  <form onSubmit={handleAddNote} className="flex gap-2">
                    <input
                      type="text"
                      placeholder="Add executive update or follow-up status note..."
                      value={noteText}
                      onChange={(e) => setNoteText(e.target.value)}
                      className="flex-1 px-4 py-3 bg-navy-950/60 border border-navy-800 rounded-xl text-sm placeholder-slate-500 text-white focus:outline-none focus:border-electric-500 transition-colors"
                    />
                    <button
                      type="submit"
                      className="px-4 py-3 rounded-xl bg-electric-600 hover:bg-electric-700 text-white transition-colors flex items-center gap-1.5 text-sm font-semibold"
                    >
                      <Send className="w-4 h-4" />
                      <span>Post</span>
                    </button>
                  </form>

                  {/* Notes history list */}
                  <div className="space-y-4">
                    {notes.map((note: any, idx: number) => (
                      <div key={idx} className="p-4 rounded-xl bg-navy-950/40 border border-navy-850 space-y-2">
                        <div className="flex items-center justify-between text-xs text-slate-400">
                          <span className="font-bold text-slate-300">{note.author}</span>
                          <span>{note.date}</span>
                        </div>
                        <p className="text-slate-300 text-xs leading-relaxed">{note.text}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}
